name: Test

on:
  push:
  pull_request:

jobs:
  spec:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install dependencies
        run: shards install
      - name: Check formatting
        run: crystal tool format --check src spec
      - name: Run tests
        run: crystal spec
